<<<<<<< Updated upstream
=======
# compose.yaml
>>>>>>> Stashed changes
services:
  api:
    build:
      context: .
      target: builder
    container_name: healthgen-conversation-fsm
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"