version: "3.8"
services:

  db:
    image: postgres:15
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${DB_PORT}:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on:
      - backend

volumes:
  db-data: