"""Add conversation_states table

Revision ID: 145592be1289
Revises: c29d2c9f90c6
Create Date: 2025-05-20 04:39:17.757734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '145592be1289'
down_revision: Union[str, None] = 'c29d2c9f90c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_states',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_conversation_states_chat_id'), 'conversation_states', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_states_chat_id'), table_name='conversation_states')
    op.drop_table('conversation_states')
    # ### end Alembic commands ###
