# backend/alembic/versions/8dfaff079983_add_explicit_columns_to_conversation_.py

"""add explicit columns to conversation_states

Revision ID: 8dfaff079983
Revises: 145592be1289
Create Date: 2025-05-30 02:39:10.158226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dfaff079983'
down_revision: Union[str, None] = '145592be1289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_states', sa.Column('name', sa.String(), nullable=True))
    op.add_column('conversation_states', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('conversation_states', sa.Column('allergy', sa.Boolean(), nullable=True))
    op.add_column('conversation_states', sa.Column('selected_slot', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_states', 'selected_slot')
    op.drop_column('conversation_states', 'allergy')
    op.drop_column('conversation_states', 'age')
    op.drop_column('conversation_states', 'name')
    # ### end Alembic commands ###
